import * as fs from 'fs';
import type { Sprite, PixelGrid, DirectionFrames } from '@maldoror/protocol';
import { RESOLUTIONS } from '@maldoror/protocol';
import type { NPCRecord } from '@maldoror/protocol';
import { db, schema } from '@maldoror/db';
import { eq } from 'drizzle-orm';
import {
  ensureNPCDir,
  getNPCPngPath,
  savePixelGridAsPng,
  loadPngAsPixelGrid,
  deleteNPCPngs,
} from './png-storage.js';
import { despeckleSpriteFrame } from './sprite-hygiene.js';

const DIRECTIONS = ['up', 'down', 'left', 'right'] as const;

/**
 * NPC data with sprite for creation
 */
export interface NPCCreateData {
  creatorId: string;
  name: string;
  prompt: string;
  spawnX: number;
  spawnY: number;
  roamRadius?: number;
  playerAffinity?: number;
  sprite: Sprite;
}

/**
 * Generate a default personality from the visual prompt
 */
function generateDefaultPersonality(prompt: string): string {
  // Simple rule-based personality generation
  // The real personality will be generated by the migration script or LLM later
  const keywords = prompt.toLowerCase();

  if (keywords.includes('sage') || keywords.includes('wizard') || keywords.includes('wise')) {
    return 'A wise and contemplative soul who shares cryptic wisdom with those who seek it.';
  }
  if (keywords.includes('merchant') || keywords.includes('trader')) {
    return 'A shrewd but fair trader who loves to haggle and share tales of distant lands.';
  }
  if (keywords.includes('fairy') || keywords.includes('sprite') || keywords.includes('magical')) {
    return 'A mischievous and playful spirit who delights in harmless pranks and spreading joy.';
  }
  if (keywords.includes('cat') || keywords.includes('dog') || keywords.includes('animal')) {
    return 'A curious creature who explores the world with wonder and befriends kind travelers.';
  }
  if (keywords.includes('dark') || keywords.includes('shadow') || keywords.includes('mysterious')) {
    return 'A mysterious figure who speaks in riddles and knows secrets of the world.';
  }
  if (keywords.includes('warrior') || keywords.includes('knight') || keywords.includes('guard')) {
    return 'A vigilant protector who values honor and keeps watch over the realm.';
  }

  return 'A curious inhabitant of Maldoror who enjoys wandering and chatting with travelers.';
}

/**
 * Create a new NPC and save its sprite to disk
 * Creates both an npcs record (for old NPC manager) and a users record (for new NPCBotManager)
 * Returns the created NPC record
 */
export async function createNPC(data: NPCCreateData): Promise<NPCRecord> {
  // Insert NPC record into database (for backwards compatibility)
  const [npcRecord] = await db.insert(schema.npcs).values({
    creatorId: data.creatorId,
    name: data.name,
    prompt: data.prompt,
    spawnX: data.spawnX,
    spawnY: data.spawnY,
    roamRadius: data.roamRadius ?? 15,
    playerAffinity: data.playerAffinity ?? 50,
    modelUsed: 'gpt-image-1-mini',
  }).returning();

  if (!npcRecord) {
    throw new Error('Failed to create NPC record');
  }

  // Also create a user record for the new NPCBotManager
  // This allows the NPC to be managed by the LLM-powered bot system
  try {
    // Check if username is taken
    const existingUser = await db
      .select()
      .from(schema.users)
      .where(eq(schema.users.username, data.name))
      .limit(1);

    const username = existingUser.length > 0
      ? `${data.name}_${Math.random().toString(36).substring(2, 6)}`
      : data.name;

    await db.insert(schema.users).values({
      id: npcRecord.id, // Use same ID for sprite file compatibility
      username,
      isNpc: true,
      personality: generateDefaultPersonality(data.prompt),
      goals: ['Explore the area', 'Greet players who pass by', 'Have friendly conversations'],
      visualPrompt: data.prompt,
      aiProvider: 'openai',
      aiModel: 'gpt-4o-mini',
      decisionIntervalMs: 300000, // 5 minutes
      spawnX: data.spawnX,
      spawnY: data.spawnY,
      roamRadius: data.roamRadius ?? 15,
      npcCreatorId: data.creatorId,
    });

    // Create player_state
    await db.insert(schema.playerState).values({
      userId: npcRecord.id,
      x: data.spawnX,
      y: data.spawnY,
      direction: 'down',
      isOnline: false,
    });

    console.log(`[NPC] Created NPC user "${username}" for NPCBotManager`);
  } catch (error) {
    // Log but don't fail - the old NPC system will still work
    console.error('[NPC] Failed to create user record for NPC:', error);
  }

  // Save sprite to disk
  await saveNPCSpriteToDisk(npcRecord.id, data.sprite);

  console.log(`[NPC] Created NPC "${data.name}" at (${data.spawnX}, ${data.spawnY})`);

  return npcRecord as NPCRecord;
}

/**
 * Save an NPC sprite to disk as individual PNG files per frame/resolution
 */
export async function saveNPCSpriteToDisk(npcId: string, sprite: Sprite): Promise<void> {
  ensureNPCDir(npcId);

  let totalFiles = 0;
  let totalSize = 0;

  // For each direction and frame
  for (const direction of DIRECTIONS) {
    for (let frameNum = 0; frameNum < 4; frameNum++) {
      // Save each resolution as a separate PNG
      for (const resolution of RESOLUTIONS) {
        // Get pixels from the appropriate resolution
        let pixels: PixelGrid | undefined;
        const resKey = String(resolution);

        if (sprite.resolutions?.[resKey]) {
          const dirFrames = sprite.resolutions[resKey][direction];
          pixels = dirFrames?.[frameNum];
        } else if (resolution === 256) {
          // Fall back to base frames for resolution 256
          pixels = sprite.frames[direction]?.[frameNum];
        }

        if (!pixels) continue;

        const filePath = getNPCPngPath(npcId, direction, frameNum, resolution);
        await savePixelGridAsPng(pixels, filePath);

        totalFiles++;
        try {
          const stat = await fs.promises.stat(filePath);
          totalSize += stat.size;
        } catch {
          // Ignore stat errors
        }
      }
    }
  }

  console.log(`[NPC] Saved sprite for ${npcId}: ${totalFiles} PNGs (${(totalSize / 1024).toFixed(1)}KB total)`);
}

/**
 * Load a single NPC sprite frame at a specific resolution
 */
export async function loadNPCFrame(
  npcId: string,
  direction: string,
  frameNum: number,
  resolution: number
): Promise<PixelGrid | null> {
  const filePath = getNPCPngPath(npcId, direction, frameNum, resolution);

  try {
    return await loadPngAsPixelGrid(filePath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    console.error(`[NPC] Failed to load frame ${direction}_${frameNum}@${resolution} for ${npcId}:`, error);
    return null;
  }
}

/**
 * Load a full NPC sprite from disk
 * Only loads base resolution (256) - renderer handles scaling
 */
export async function loadNPCSpriteFromDisk(npcId: string): Promise<Sprite | null> {
  // Check if files exist by trying to load one frame
  const testFrame = await loadNPCFrame(npcId, 'down', 0, 256);
  if (!testFrame) {
    return null;
  }

  const width = testFrame[0]?.length ?? 256;
  const height = testFrame.length;

  // Initialize the sprite structure
  const sprite: Sprite = {
    width,
    height,
    frames: {
      up: [[], [], [], []] as unknown as DirectionFrames,
      down: [[], [], [], []] as unknown as DirectionFrames,
      left: [[], [], [], []] as unknown as DirectionFrames,
      right: [[], [], [], []] as unknown as DirectionFrames,
    },
    resolutions: {},
  };

  // Load all base resolution frames
  for (const direction of DIRECTIONS) {
    for (let frameNum = 0; frameNum < 4; frameNum++) {
      const pixels = await loadNPCFrame(npcId, direction, frameNum, 256);
      if (pixels) {
        // Strip baked-in dark alpha fringe (see sprite-hygiene.ts)
        sprite.frames[direction][frameNum] = despeckleSpriteFrame(pixels);
      }
    }
  }

  return sprite;
}

/**
 * Load all NPCs from database
 */
export async function loadAllNPCs(): Promise<NPCRecord[]> {
  const records = await db.select().from(schema.npcs);
  console.log(`[NPC] Loaded ${records.length} NPCs from database`);
  return records as NPCRecord[];
}

/**
 * Get an NPC by ID
 */
export async function getNPC(npcId: string): Promise<NPCRecord | null> {
  const [record] = await db.select().from(schema.npcs).where(eq(schema.npcs.id, npcId));
  return (record as NPCRecord) || null;
}

/**
 * Delete an NPC and its sprite files
 */
export async function deleteNPC(npcId: string): Promise<void> {
  // Delete PNG files
  await deleteNPCPngs(npcId);

  // Delete database record
  await db.delete(schema.npcs).where(eq(schema.npcs.id, npcId));

  console.log(`[NPC] Deleted NPC ${npcId}`);
}

/**
 * Check if an NPC sprite exists on disk
 */
export async function npcSpriteExists(npcId: string): Promise<boolean> {
  const frame = await loadNPCFrame(npcId, 'down', 0, 256);
  return frame !== null;
}
